### ISSUE TITLE
Identifier and IdentifierSystem

### ISSUE THREAD

**Issue by Fak3** [uncefact/spec-untp#137] opened 2024-07-29 18:36 UTC
Products and Organizations can have multiple identifiers expressed using various identifier schemes.

## Current model issues

As currently suggested in DigitalproductPassport.md, identifier is described with idScheme, idValue, idSchemeName:
```json
{
      "id": "https://abr.business.gov.au/ABN/View?abn=90664869327",
      "name": "ACME Pty Ltd",
      "idValue": "90664869327",
      "idScheme": "abr.business.gov.au",
      "idSchemeName": "Australian Business Number"
}
```
The problem is that those properties are assigned not to the specific identifier, but to the entity, which can have multiple identifiers with different identification schemes. 

Let's imagine this json-ld data is stored and processed by owl inferencer. And in their graph database they already reflect that this organization have two identifiers:
```turtle
<did:web:acme.au> <owl:sameAs> <https://abr.business.gov.au/ABN/View?abn=90664869327> .
```
Processing this new data according to owl:sameAs semantics, the owl inferencer will add new triples to the graph:
```turtle
<did:web:acme.au> <idSchemeName> "Australian Business Number" .
```
This does not make sense, as it means Decentralized Identifier conforms to ABN identifier scheme.

## Proposed model
To resolve the issue, identifiers should be described separately from the entity itself:
```json
"id": "did:web:company.au",
"identifier": [{
  "notation": "115378.76",
  "isPartOf": {
     "id": "augov:ABN",
     "type": "IdentifierSystem",
     "name": "Australian Business Number"
  }
}, {
  "notation": "679429",
  "isPartOf": {
     "id": "gs1:GLN",
     "type": "IdentifierSystem",
     "name": "GS1 Global Location Number"
  }
}]
```
 In the example above I omitted `"type": "Identifier"` but included explicit `"type": "IdentifierSystem"`. Whether we should require those types explicitly declared in documents is debatable.

I suggest reusing existing vocabularies:

* Class [`adms:Identifier`](https://www.w3.org/TR/vocab-adms/#identifier) based on the UN/CEFACT Identifier class. 
   Properties: 
    * _skos:notation_ -- string with the literal value of the identifier 
    * _dcterms:isPartOf_ -- reference to the `ebg:IdentifierSystem`
    
> An important point to note is that properties of adms:Identifier are properties of the Identifier, not the resource that it identifies or the agency that issued it. 

* Class `ebg:IdentifierSystem` from [BusinessGraph vocabulary](https://github.com/euBusinessGraph/eubg-data)
  Definition from [ontology.ttl](https://github.com/euBusinessGraph/eubg-data/blob/master/model/ebg-ontology.ttl):  "A system managed by a publisher (e.g., a register or  agency) that is used to issue identifiers to entities (companies, persons, etc)."
  Properties:
    *  _schema:name_ -- label for humans
    * _dcterms:creator_ --  Agent that issues identifiers and then keeps them in a database (register), and who issued a specific identifier

* Property [`adms:identifier`](https://www.w3.org/TR/vocab-adms/#adms-identifier) that links a resource to the `adms:Identifier`.

There are other properties in the BusinessGraph ontology wich can be reused, for ex jurisdiction, issuance and expiration date, etc... We should probably add them to our json-ld context file as well.

Related to #135

Similar issue was discussed on traceability vocab: https://github.com/w3c-ccg/traceability-vocab/issues/944

**Comment by Fak3** [comment] 2024-07-29 18:38
@VladimirAlexiev, as a coauthor of BuisnessGaph ontology, can you please comment if the proposed reuse of it is adequate?

**Comment by Fak3** [comment] 2024-08-03 21:35
@VladimirAlexiev at https://github.com/w3c-ccg/traceability-vocab/issues/944 you proposed to use `schema:PropertyValue` instead of more specific `adms:Identifier`. Is there any reason to prefer the former?

**Comment by onthebreeze** [comment] 2024-08-15 05:12
Not sure how to resolve this one.  @Fak3 says 

As currently suggested in DigitalproductPassport.md, identifier is described with idScheme, idValue, idSchemeName:

```
{
      "id": "https://abr.business.gov.au/ABN/View?abn=90664869327",
      "name": "ACME Pty Ltd",
      "idValue": "90664869327",
      "idScheme": "abr.business.gov.au",
      "idSchemeName": "Australian Business Number"
}
```
The problem is that those properties are assigned not to the specific identifier, but to the entity, which can have multiple identifiers with different identification schemes.

I don't think I agree with the assertion that these properties are not specific to the identifier.  

the id is the full URI of the identifier - globally unique
the name is human readable name as registered with that speecific registry
the idValue is the identifier as it is know within the registry - unique only within the registry.
the idScheme is the URI of the registry itself.
the idSchemeName is the human readable name of the id scheme.

Lets imagine the same business entity has another identifier in another business register 

```
{
      "id": "https://gln.gs1.org/1234567",
      "name": "ACME Industries",
      "idValue": "1234567",
      "idScheme": "gln.gs1.org",
      "idSchemeName": "Global Location Number"
}
```
Totally different values for every property.  There in nothing that demands an entity to use their national registered legal entity name when creating a GLN with GS1 - they might choose something more like their trading name.

Could you clarify the problem here?

**Comment by Fak3** [comment] 2024-08-15 10:19
> Lets imagine the same business entity has another identifier in another business register

1. Initially the application has two distinct graph nodes for the same entity:

```json
{
      "id": "https://gln.gs1.org/1234567",
      "name": "ACME Industries",
      "idValue": "1234567",
      "idScheme": "gln.gs1.org",
      "idSchemeName": "Global Location Number"
}
```
and
```json
{
      "id": "https://abr.business.gov.au/ABN/View?abn=90664869327",
      "name": "ACME Pty Ltd",
      "idValue": "90664869327",
      "idScheme": "abr.business.gov.au",
      "idSchemeName": "Australian Business Number"
}
```

2. Some third-party registry then sends to the application statement of equality between the two identifiers (as they represent the same entity):

```json
{
  "id": "https://abr.business.gov.au/ABN/View?abn=90664869327"
  "owl:sameAs": "https://gln.gs1.org/1234567"
 }
```

3. Application processes `owl:sameAs` according to its semantics, which instructs to copy all the properties from node1 to node2 and vice versa. Now it has two nodes with all their properties merged:

```json
{
      "id": "https://gln.gs1.org/1234567",
      "owl:sameAs": "https://abr.business.gov.au/ABN/View?abn=90664869327", 
      "name": ["ACME Industries", "ACME Pty Ltd"],
      "idValue": ["1234567", "90664869327"],
      "idScheme": ["gln.gs1.org", "abr.business.gov.au"],
      "idSchemeName": ["Global Location Number", "Australian Business Number"]
}
```
and
```json
{
      "id": "https://abr.business.gov.au/ABN/View?abn=90664869327",
      "owl:sameAs": "https://gln.gs1.org/1234567", 
      "name": ["ACME Industries", "ACME Pty Ltd"],
      "idValue": ["1234567", "90664869327"],
      "idScheme": ["gln.gs1.org", "abr.business.gov.au"],
      "idSchemeName": ["Global Location Number", "Australian Business Number"]
}
```

Thus, the original intent of assigning `idScheme` to single node with particular identifier is violated by applying `owl:sameAs` according to its semantics. I.e the resulting graph will contain the nonsense triple:
` <https://gln.gs1.org/1234567> <idScheme> "abr.business.gov.au" .`

The issue here is that with the current data model intended separation between the distinctly identified nodes can't be ensured. The RDF states that properties describe **entity itself**, while we are currently assuming properties describe **entity's identifier**, violating that rule.

So my proposal is to separate identifier metadata into its own node, which explicitly describes identifier of that original entity.

**Comment by Fak3** [comment] 2024-08-15 10:43
>   Lets imagine the same business entity has another identifier in another business register

 1.   Initially the application has two distinct graph nodes for the same entity:

```json
{
      "id": "https://gln.gs1.org/1234567",
      "name": "ACME Industries",
      "idValue": "1234567",
      "idScheme": "gln.gs1.org",
      "idSchemeName": "Global Location Number"
}
```

and

```json
{
      "id": "https://abr.business.gov.au/ABN/View?abn=90664869327",
      "name": "ACME Pty Ltd",
      "idValue": "90664869327",
      "idScheme": "abr.business.gov.au",
      "idSchemeName": "Australian Business Number"
}
```

  1.  Some third-party registry then sends to the application statement of equality between the two identifiers (as they represent the same entity):

```json
{
  "id": "https://abr.business.gov.au/ABN/View?abn=90664869327"
  "owl:sameAs": "https://gln.gs1.org/1234567"
 }
```

1.    Application processes owl:sameAs according to its semantics, which instructs to copy all the properties from node1 to node2 and vice versa. Now it has two nodes with all their properties merged:

```json
{
      "id": "https://gln.gs1.org/1234567",
      "owl:sameAs": "https://abr.business.gov.au/ABN/View?abn=90664869327", 
      "name": ["ACME Industries", "ACME Pty Ltd"],
      "idValue": ["1234567", "90664869327"],
      "idScheme": ["gln.gs1.org", "abr.business.gov.au"],
      "idSchemeName": ["Global Location Number", "Australian Business Number"]
}
```

and

```json
{
      "id": "https://abr.business.gov.au/ABN/View?abn=90664869327",
      "owl:sameAs": "https://gln.gs1.org/1234567", 
      "name": ["ACME Industries", "ACME Pty Ltd"],
      "idValue": ["1234567", "90664869327"],
      "idScheme": ["gln.gs1.org", "abr.business.gov.au"],
      "idSchemeName": ["Global Location Number", "Australian Business Number"]
}
```

Thus, the original intent of assigning `idScheme` to single node with particular identifier is violated by applying `owl:sameAs` according to its semantics. I.e the resulting graph will contain the nonsense triple:
` <https://gln.gs1.org/1234567> <idScheme> "abr.business.gov.au" .`

The issue here is that with the current data model intended separation between the distinctly identified nodes can't be ensured. The RDF states that properties describe entity itself, while we are currently assuming properties describe entity's identifier, violating that rule.

So my proposal is to separate identifier metadata into its own node, which explicitly describes identifier of that original entity. In that proposal identifier becomes a separate entity (graph node) of itself, linked to the original entity (graph node) which it describes via `adms:identifier` property.

**Comment by VladimirAlexiev** [comment] 2024-08-15 13:39
In addition, it makes sense to split out a separate `IdentifierSystem` node. 
Otherwise different `Identifier` nodes can have inconsitent info about the scheme that they use.

Currently you have only 2 props:
```
      "idScheme": "abr.business.gov.au",
      "idSchemeName": "Australian Business Number"
```
but in the future you may have more, eg:
- who issues it
- where is its home page
- what is the URL pattern for company pages in that register
- is it unique, unambiguous, opaque, etc

You can read about it in the euBusinessGraph Semantic Data Model https://docs.google.com/document/d/1dhMOTlIOC6dOK_jksJRX0CB-GIRoiYY6fWtCnZArUhU/edit#heading=h.hofh07qhoz6m

**Comment by onthebreeze** [comment] 2024-08-18 02:25
OK I'll separate out the id scheme into it's own class with it's own "id" so that the graph will have a seaprate node for identity schemes.

**Comment by Fak3** [comment] 2024-08-24 14:43
This issue still exists on current published spec:
Example DPP from https://uncefact.github.io/spec-untp/docs/specification/DigitalProductPassport:
```json
"issuer": {
   "type": "CredentialIssuer",
   "id": "did:web:identifiers.acme.com:12345",
   "name": "ACME industries",
   "otherIdentifiers": [{
      "type": "Entity",
      "id": "https://abr.business.gov.au/ABN/View?abn=90664869327",
      "name": "ACME Pty Ltd",
      "idValue": "90664869327",
      "idScheme": "abr.business.gov.au",
      "idSchemeName": "Australian Business Number"
    }]
},
```

Should be:
```json
"issuer": {
   "type": "CredentialIssuer",
   "id": "did:web:identifiers.acme.com:12345",
   "name": "ACME industries",
   "identifier": [{
      "type": "Identifier",
      "notation": "https://abr.business.gov.au/ABN/View?abn=90664869327",
      "name": "ACME Pty Ltd",
      "isPartOf": {
           "id": "abr.business.gov.au/ABN",
           "type": "IdentifierSystem",
           "name": "Australian Business Number"
       }
    }]
},
```

**Comment by onthebreeze** [comment] 2024-08-24 15:19
I missed to update the sample snippet on the the page.  But the model and schema and sample at the top of the page is different -please check https://uncefact.github.io/spec-untp/assets/files/untp-digital-product-passport-v0.3.6-86c6ee585e0905f8871b40838616f9ff.json

**Comment by Fak3** [comment] 2024-08-24 16:20
> I missed to update the sample snippet on the the page. But the model and schema and sample at the top of the page is different -please check https://uncefact.github.io/spec-untp/assets/files/untp-digital-product-passport-v0.3.6-86c6ee585e0905f8871b40838616f9ff.json

This sample has the same issue:
```json
"issuer": {
    "type": [
      "CredentialIssuer"
    ],
    "id": "did:web:identifiers.example-company.com:12345",
    "name": "Example Company Pty Ltd",
    "otherIdentifiers": [
      {
        "type": [
          "Entity"
        ],
        "id": "https://business.gov.au/ABN/View?abn=1234567890",
        "name": "Sample Company Pty Ltd",
        "registeredId": "1234567890",
        "idScheme": {
          "type": [
            "IdentifierScheme"
          ],
          "id": "https://business.gov.au/ABN/",
          "name": "Australian Business Number"
        }
      }
    ]
  },
  ```
  
  Should be:
  
  ```json
"issuer": {
    "type": "CredentialIssuer",
    "id": "did:web:identifiers.example-company.com:12345",
    "name": "Example Company Pty Ltd",
    "identifier": [
      {
        "type": "Identifier",
        "notation": "https://business.gov.au/ABN/View?abn=1234567890",
        "name": "Sample Company Pty Ltd",        
        "isPartOf": {
          "type": "IdentifierSystem",
          "id": "https://business.gov.au/ABN-HTTP",
          "name": "Australian Business Number URL"
        }
      },
      {
        "type": "Identifier",
        "notation": "1234567890",
        "name": "Sample Company Pty Ltd",        
        "isPartOf": {
          "type": "IdentifierSystem",
          "id": "https://business.gov.au/ABN",
          "name": "Australian Business Number"
        }
      }
    ]
  },
  ```
Also note that "https://business.gov.au/ABN-HTTP" and plain "https://business.gov.au/ABN" are different IdentifierSystems

**Comment by onthebreeze** [comment] 2024-09-02 00:06
I think there might be a linked data architecture or strategy question behind this issue.  I think it boils down to a question of whether entities should be merged with there is some kind of equivalence declared or only when identifiers are exactly identical.  If an entity with ID = abn.gov.au/123454567 declares "otherIidentifiers" like gs1.org/gln/9876543 then does this mean they are the same and all data about abn.gov.au/123454567 and gs1.org/gln/9876543 should be merged?

* @Fak3 suggests that the declaration of other identifiers is a declaration of equivalence (like "owl:sameAs") and that common practice will be to merge the two entities into one.  And, when that is done, there will be logical inconsistencies.
* my experience on the other hand is that this is a very common scenario (two different identifiers about what "might" be the same thing") and that merging is always bad practice. Government agencies face this exact scenario all the time and have learned the hard way not to merge because it is then almost impossible to split.  

In the example given, an ABN is an Australian national business tax registration number.  A GLN is a GS1 identifier for a logistics location.  In some cases where a business has only one operating location these two IDs could resolve to very similar things.  But even so, a legal tax registration is not the same as a logistics location.  Also, as soon as the business opens a second location and creates another GLN there will be far worse inconsistencies associated with any merge. 

I suggest add some words in the [graphs](https://uncefact.github.io/spec-untp/docs/design-patterns/TrustGraphs) section of UNTP to emphasise that meta data of two entities should only be merged when the declared identifiers are identical (eg two instances of gs1.org/gln/9876543) but never when two different identifiers are declared to be related and possibly equivalent.

**Comment by Fak3** [comment] 2024-09-02 10:20
Section "9.2 Equivalence" of gs1 digital link spec https://www.gs1.org/docs/Digital-Link/GS1_Digital_link_Standard_i1.1.pdf mentions use of owl:sameAs
![Screenshot_20240902_151359](https://github.com/user-attachments/assets/81904942-54e0-4b46-b845-9245172edcd0)

As well as the section "2.3 Decompression":
![Screenshot_20240902_151201](https://github.com/user-attachments/assets/8230402b-2ff3-4f28-887a-021a090d4a23)


@philarcher @mgh128 Can you please tell if you see a realistic scenario for a single product referenced by several different gs1 links? For ex. issuer1 uses compressed link, issuer2 uses uncompressed GTIN+batch. Could both links reference the same product in two different Product Passports or Conformity Credentials?

If we forbid to process `owl:sameAs` on the verifier side, we must document that clearly in the spec. This restriction will force verifiers to to do one or a combination of the following: 
1. construct more complex SPARQL queries 
2. strip off incoming `owl:sameAs` statements 
3. apply custom graph merging rules (ignore or replace `idScheme` property)

**Comment by onthebreeze** [comment] 2024-09-02 12:23
The gs1 doc basically says "use owl:sameAs" with care - only when you are really sure the two different t identifiers refer to the same thing.

UNTP is not going to specify owl:sameAs in any scenario - that's a choice of the processor using vocabularies we don't control

UNTP can only recommend that "If two things have different identifiers then dint legę them".  I really don't understand why this is even a contentious issue?

**Comment by onthebreeze** [comment] 2024-09-02 12:44
Ok fair enough.  But where are we (ie UNTP) making any equivalence statement using owl:sameAs ?  Is there an assumption that "otherIdentifiers" or "alsoKnownAs" should be interpreted as "owl:sameAs"?

**Comment by Fak3** [comment] 2024-09-02 12:53
> Ok fair enough.  But where are we (ie UNTP) making any equivalence statement using owl:sameAs ?  Is there an assumption that "otherIdentifiers" or "alsoKnownAs" should be interpreted as "owl:sameAs"?

We do reference using GS1 digital link in our IdentityResolver.md

GS1 digital link spec mandates the owl:sameAs relationship between short and full links

**Comment by Fak3** [comment] 2024-09-02 13:02
> Hi, in the EU context the Nordic business register authority cooperation advocates the use of adms:Identifier but in the way it's been modeled in the EU Core Vocabularies:
> https://semiceu.github.io/Core-Business-Vocabulary/releases/2.2.0/#Identifier
> 
> Then again there's a reference to "the UN/CEFACT class with the same name" - but in the UN/CEFACT CCL these attributes are actually includet in the uDT (IdentifierType) - and there they are indeed mostly properties of the "Identification Scheme".
 
Thank you! I believe it is important to align with EU Core business vocabulary and UN/CEFACT CCL. We should reuse same data model and have dedicated `Identifier` class for identifier metadata.

**Comment by onthebreeze** [comment] 2024-09-02 13:11
The uncefact ccl defines an identifier data type that mixes both the ID of the entity and the ID of the identifier scheme in one class.  Which is what I thought was exactly what you are objecting to?

**Comment by Fak3** [comment] 2024-09-02 13:15
> The uncefact ccl defines an identifier data type that mixes both the ID of the entity and the ID of the identifier scheme in one class.  Which is what I thought was exactly what you are objecting to?  

No, as we discussed on slack, separating identifierSystem metadata is not that important, as it does not lead to inconsistent graph.

**Comment by onthebreeze** [comment] 2024-09-02 13:17
But surely we are talking about two different questions here. Short and full links are just different technical representations of exactly the same registry entry.  There's not even a merge question here because they both point to the exact same entry. 

But whether or not to merge two entries across two different registers is not the same question.

**Comment by Fak3** [comment] 2024-09-02 13:28
> But surely we are talking about two different questions here. Short and full links are just different technical representations of exactly the same registry entry.  There's not even a merge question here because they both point to the exact same entry. 
> 
> But whether or not to merge two entries across two different registers is not the same question.  

"http://example.org/gtin/054123450013/lot/ABC%26%2B123?3103=000189&3923=2172"
And "(3103)000189(01)05412345000013(3923)2172(10)ABC&+123" reference the same product but follow different identifier schemes with different parsing rules, so it is incorrect to say that the first has the compressed identifier schema and the second has a full one

**Comment by Fak3** [comment] 2024-09-02 13:58
> Those are not different schemes. They are both the same GTIN. Just different technical representations of the same thing. "Scheme" does not refer to a technical syntax. A different scheme means a different register (like ABN vs GLN).

For the example of same schema and different registries, there is an european union open data endpoint: https://data.europa.eu/data/sparql?locale=en

queriying it with `SELECT distinct ?d ?x WHERE { ?d owl:sameAs ?x . ?d a vcard:Organization . } LIMIT 1000`
Reveals that 
```
<http://data.brreg.no/enhetsregisteret/enhet/950037687> <owl:sameAs> <https://register.geonorge.no/organisasjoner/norsk-institutt-for-naturforskning> 
```
i.e there are two registries: 1. data.brreg.no 2. register.geonorge.no
And they state that those two organization identifiers are strictly equivalent.

Do we ever encounter such cases in untp?

**Comment by mgh128** [comment] 2024-09-02 14:07
> > But surely we are talking about two different questions here. Short and full links are just different technical representations of exactly the same registry entry.  There's not even a merge question here because they both point to the exact same entry. 
> > 
> > But whether or not to merge two entries across two different registers is not the same question.  
> 
> "http://example.org/gtin/054123450013/lot/ABC%26%2B123?3103=000189&3923=2172"
> And "(3103)000189(01)05412345000013(3923)2172(10)ABC&+123" reference the same product but follow different identifier schemes with different parsing rules, so it is incorrect to say that the first has the compressed identifier schema and the second has a full one




http://example.org/01/054123450013/10/ABC%26%2B123?3103=000189&3923=2172

is an example of a fully uncompressed GS1 Digital Link URI.

(3103)000189(01)05412345000013(3923)2172(10)ABC&+123

is an example of a corresponding GS1 element string using parentheses around the GS1 Application Identifiers.  It is not a GS1 Digital Link URI nor any kind of compressed format.

It would be OK to express an owl:sameAs relationship between an uncompressed GS1 Digital Link URI and the exactly equivalent compressed or partially compressed GS1 Digital Link URIs but only if they identify the same thing, i.e. if the fully/partially compressed GS1 Digital Link URI encodes the same combination of GS1 Application Identifiers and their values.

In practice, GS1 does not currently recommend the use of fully compressed or partially compressed GS1 Digital Link URIs within 2D barcodes for products.  In most situations, a cautious use of upper-case alphanumeric characters and very few symbol characters enables efficient QR encoders to use the "alphanumeric" mode rather than "binary/byte" mode and this typically achieves an equivalent reduction in size of QR Code without the complexity of handling compression or decompression.

I would expect that when GS1 Digital Link URIs are used within Linked Data or within Verifiable Credentials, it would be the fully uncompressed format, without any compression.

I hope this helps.

**Comment by VladimirAlexiev** [comment] 2024-09-04 05:07
I think the discussion went astray. 
The gist is that we need different classes for entity and Identifier .
As for IdentifierSystem, that is optional, depending on whether we need to:
- express characteristics of the system that don't belong to an individual Identifier (I.e. beyond dateIssued, dateExpiry). Eg the GLEI RAL ID is such.
- express when one agency issues different kinds of identifiers. That's quite common and you can see examples in GLEI RAL

**Comment by onthebreeze** [comment] 2024-09-04 05:27
I still do not understand. Every node in a graph needs an identifier.  So if there is an Entity class it must have an id.  Separately that id may be issued under a governed scheme which itself has an id.  

So I understand if the requirement is "entities (with id) should be a separate class from identifierScheme (with it's own id)". But I don't understand what it means to say "we need sepaate classes for entity and identifier". If the id of an entity is in a separate class then what is the id of the entity class??

**Comment by Fak3** [comment] 2024-09-04 06:53
@onthebreeze graph node must have exactly one **primary id**. Also it can have additional identifiers associated with it via properties.

Instance of a Product class, as an abstract concept can be independently described by multiple parties (issuers), while each party independently can choose a different **primary id** for the graph node which represents that same instance of a Product class in their own separate graph.

Verifier receives those separate graphs and some additional data which suggests that those parties indeed chose different **primary id** for the same Product instance. Now knowing that those ids refer to the same entity, he can correctly apply business rules, treating properties of those separate graph nodes as if they belong to the same entity.

So one issuer chose one identifier of an entity and promoted it to be graph node's **primary id**. Then, as currently suggested, he associates <idScheme> and all other product properties with this primary id. Note here is that all of these properties describe a particular physical product instance, except for idScheme which describes the abstract arbitrarily chosen primary id of a node in the graph.

Now the verifier attempting to apply business logic must be careful, because it faces data with physical properties of a product, which does not depend on the issuers choice, mixed with multiple idScheme properties, each one of idScheme is only valid for a particular choice of node's **primary id** of the issuer.

**Comment by Fak3** [comment] 2024-09-16 11:36
I have just stumbled upon a recommendation to use `adms:identifier` property to link DCAT datasets in section 5.1.2 of the report on [Open government data ecosystem in Europe ](https://joinup.ec.europa.eu/sites/default/files/inline-files/dcat_ap_carrara_dekkers_dittwald_dutkowski_glikman_loutas_peristeras_wyns_v3.5.pdf)

![Screenshot_2024-09-16-16-31-38-358-edit_org.mozilla.firefox.jpg](https://github.com/user-attachments/assets/28b4f1f0-9bbe-4e56-b66d-549478abb27b)

**Comment by mgh128** [comment] 2024-09-16 12:15
Currently (and probably for the foreseeable future), GS1 only recommends
the use of uncompressed GS1 Digital Link URIs - neither fully compressed or
partially compressed GS1 Digital Link URIs are supported by GS1 application
standards.

However, it would still be acceptable to use an owl:sameAs relationship
between an uncompressed GS1 Digital Link URI formed from a registered
domain name and the corresponding canonical GS1 Digital Link URI using
id.gs1.org as the hostname.

For Digital Product Passport data, I fully expect that factual claims will
be expressed at various granularities of identification - some facts may
apply to every instance of a product having that GTIN, while others may be
specific to a specific GTIN+Batch and others may be specific to one
individual product instance identified by GTIN+SerialNumber.

An AIDC data carrier such as a 2D barcode might encode GTIN, CPV,
Batch/Lot, SerialNumber but some data (such as EPCIS event data for supply
chain traceability / visibility) might only use GTIN+SerialNumber when
reporting that an individual object was observed at a location or
participated in a particular business process step.  That's because
GTIN+SerialNumber provides the finest granularity of identification and
from those details, CPV or Batch/Lot should be accessible via lookup of the
master data for that GTIN+SerialNumber.

**Comment by onthebreeze** [comment] 2024-09-29 10:44
I think the outcome of all this is 

* `Identifier` and `IdentifierScheme` should be different node objects - this is now the case.
* Implementers should not assume that multiple identifiers listed for a given product/facility/organisation are semantically identical.  AlsoKnownAs is not the same as owl:sameAs.  

Closing this unless there are objections.

**Closed by onthebreeze** 2024-09-29 10:44 UTC
Labels: Pending Close
